export const LIST_RICKMORTY = "LIST_RICKMORTY"
export const LIST_RICKMORTY_SUCCESS = "LIST_RICKMORTY_SUCCESS"
export const LIST_RICKMORTY_ERROR = "LIST_RICKMORTY_ERROR"

export const LIST_RICKMORTY_ID = "LIST_RICKMORTY_ID"
export const LIST_RICKMORTY_ID_SUCCESS = "LIST_RICKMORTY_ID_SUCCESS"
export const LIST_RICKMORTY_ID_ERROR = "LIST_RICKMORTY_ID_ERROR"
